import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "../Application/components/NavBar";
import { ApplicationContextProvider } from "../Application/Application.context";
import { WorkContextProvider } from "../Work/work.context"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ApplicationContextProvider>
             <WorkContextProvider>
               <NavBar/>
               {children}
             </WorkContextProvider>
          </ApplicationContextProvider>
      </body>
    </html>
  );
}
