CREATE DATABASE DanBookings;
USE DanBookings;
-- FILTERS
CREATE TABLE CATEGORY(
 CODE VARCHAR(50) PRIMARY KEY,
 icon VARCHAR(255), 
 NAME VARCHAR(50)
);

CREATE TABLE SUB_CATEGORY(
  ID_SUB_CATEGORY VARCHAR(250) PRIMARY KEY DEFAULT(UUID()),
  CATEGORY_REF VARCHAR(250),
  CODE VARCHAR(250),
  NAME VARCHAR(255),
  FOREIGN KEY (CATEGORY_REF) REFERENCES CATEGORY(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);
-- PRODUCT
CREATE TABLE WORKS (
  WO_ID VARCHAR(250) PRIMARY KEY DEFAULT(UUID()),
  WO_NAME VARCHAR(250),
  WO_URL VARCHAR(250) UNIQUE,
  CATEGORY VARCHAR(250),
  SUBCATEGORY VARCHAR(250),
  WO_ORDER INT,
  WO_VISIBLE INT DEFAULT(1)
);
CREATE TABLE WORK_DETAILS(
  WO_ID VARCHAR(250) DEFAULT(UUID()) UNIQUE,
  WO_URL VARCHAR(250) PRIMARY KEY,
  DE_DESCRIPTION VARCHAR(500),
  DE_TITLE VARCHAR(250),
  FOREIGN KEY (WO_URL) REFERENCES WORKS(WO_URL) ON DELETE CASCADE ON UPDATE CASCADE
);

-- IMGS AND FILES
CREATE TABLE MEDIAS(
  DETAILS_MEDIA_ID INT AUTO_INCREMENT PRIMARY KEY,
  TARGET_ID VARCHAR(250) COMMENT 'ID of target type media example: WO_ID,WO_URL...',
  CATEGORY VARCHAR(250) DEFAULT 'GENERIC' COMMENT 'Category type of the media target: WORKS,STORE,USERS...',
  URL_MEDIA VARCHAR(250) NOT NULL,
  TYPE_MEDIA VARCHAR(250) DEFAULT 'IMG'
);
-- USERS
CREATE TABLE USERS(
 ID_USER VARCHAR(250) PRIMARY KEY DEFAULT(UUID()),
 ID_AUTH VARCHAR(100) NOT NULL UNIQUE,
 USER_NAME VARCHAR(250) NOT NULL,
 EMAIL VARCHAR(250) UNIQUE NOT NULL,
 ROL varchar(255)
);
-- TRANSLATIONS
CREATE TABLE LANGUAGUES(
 CODE VARCHAR(10) PRIMARY KEY,
 NAME VARCHAR (250),
 flag_url VARCHAR(250),
 emoji CHAR(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
);

CREATE TABLE TRANSLATIONS(
 ID_TRANSLATION VARCHAR(250) PRIMARY KEY DEFAULT(UUID()),
 TARGET_ID VARCHAR(250),
 TEXT VARCHAR(3000),
 CATEGORY VARCHAR(250),
 LANGUAGUE_CODE VARCHAR(10),
 TYPE VARCHAR(100),
 FOREIGN KEY (LANGUAGUE_CODE) REFERENCES LANGUAGUES(CODE) 
);

SET SQL_SAFE_UPDATES = 0;

