import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "../components/NavBar";
import ProviderSession from "../context/SessionProvider";
import { PorfolioContextProvider } from "../context/PorfolioProvider";
import { ApplicationContextProvider } from "../context/AplicationProvider";
import { WorkContextProvider } from "../context/WorkProvider"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ProviderSession>
          <ApplicationContextProvider>
            <PorfolioContextProvider>
              <WorkContextProvider>
                <NavBar/>
                {children}
              </WorkContextProvider>
            </PorfolioContextProvider>
          </ApplicationContextProvider>
        </ProviderSession>
      </body>
    </html>
  );
}
