import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "../application/components/NavBar/NavBar";
import { ApplicationContextProvider } from "../application/Application.context";
import { ReactQueryProvider } from "../shared/libs/reactQuery"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReactQueryProvider>
          <ApplicationContextProvider>
               <NavBar/>
               {children}
          </ApplicationContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
