import { cookies } from 'next/headers';
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "../application/components/NavBar/NavBar";
import { ApplicationContextProvider } from "../application/Application.context";
import { ReactQueryProvider } from "../shared/libs/reactQuery"
import { LANG_LS } from '../application/application.constant';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const initialLanguage = cookieStore.get(LANG_LS)?.value || DEFAULT_LNG_APP;
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReactQueryProvider>
          <ApplicationContextProvider initialLanguage={initialLanguage}>
               <NavBar/>
               {children}
          </ApplicationContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
