CREATE DATABASE DanBookings;
USE DanBookings;
CREATE TABLE WORKS (
  WO_ID VARCHAR(250) PRIMARY KEY NOT NULL DEFAULT(UUID()),
  WO_NAME VARCHAR(250) NOT NULL,
  WO_URL VARCHAR(250) UNIQUE,
  WO_ORDER INT,
  WO_IMAGE_URL VARCHAR(250),
  WO_VISIBLE INT DEFAULT(1)
);
CREATE TABLE WORK_DETAILS(
  DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
  WO_ID VARCHAR(250),
  DE_DESCRIPTION VARCHAR(500),
  DE_TITLE VARCHAR (250),
  FOREIGN KEY(WO_ID) REFERENCES WORKS(WO_ID)
);
CREATE TABLE WORK_DETAILS_IMG(
	DETAILS_IMG_ID INT AUTO_INCREMENT PRIMARY KEY,
    WO_DETAIL_ID INT,
    URL_IMG VARCHAR(250) NOT NULL,
    FOREIGN KEY(WO_DETAIL_ID) REFERENCES WORK_DETAILS(DETAIL_ID)
);
   

