CREATE DATABASE DanBookings;
USE DanBookings;
CREATE TABLE WORKS (
  WO_ID VARCHAR(250) PRIMARY KEY DEFAULT(UUID()),
  WO_NAME VARCHAR(250),
  WO_URL VARCHAR(250) UNIQUE,
  WO_ORDER INT,
  WO_VISIBLE INT DEFAULT(1)
);
CREATE TABLE WORK_DETAILS(
  WO_ID VARCHAR(250) DEFAULT(UUID()) UNIQUE,
  WO_URL VARCHAR(250) PRIMARY KEY,
  DE_DESCRIPTION VARCHAR(500),
  DE_TITLE VARCHAR(250),
  FOREIGN KEY (WO_URL) REFERENCES WORKS(WO_URL) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MEDIAS(
  DETAILS_MEDIA_ID INT AUTO_INCREMENT PRIMARY KEY,
  TARGET_ID VARCHAR(250) COMMENT 'ID of target type media example: WO_ID,WO_URL...',
  CATEGORY VARCHAR(250) DEFAULT 'GENERIC' COMMENT 'Category type of the media target: WORKS,STORE,USERS...',
  URL_MEDIA VARCHAR(250) NOT NULL,
  TYPE_MEDIA VARCHAR(250) DEFAULT 'IMG'
);

CREATE TABLE USERS(
ID_USER VARCHAR(250) PRIMARY KEY DEFAULT(UUID()),
ID_AUTH VARCHAR(100) NOT NULL UNIQUE,
USER_NAME VARCHAR(250) NOT NULL,
EMAIL VARCHAR(250) UNIQUE NOT NULL,
ROL varchar(20) DEFAULT "USER"
);


SET SQL_SAFE_UPDATES = 0;

